---
- name: Copy maintenance configuration file to server
  template: src={{ maintenance_template_file }}
        dest=/etc/emptyhammock-maintenance.yml
        owner=root
        group=root
        mode=0644
